name: Example Dataset Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Compile and Run
        run: |
          javac -encoding UTF-8 -cp src src/acrostics/*.java
          java -cp src acrostics.Main -input data/example -language EN -mode LINE -charset utf-8 -outputSize 4000 --concise > result.tsv

      - name: Test on Mac or Ubuntu
        if: matrix.os != 'windows-latest'
        run: |
          diff -w result.tsv .github/workflows/exampleExpectedResult.tsv

      - name: Test on Windows
        if: matrix.os == 'windows-latest'
        run: |
          fc.exe result.tsv .github\workflows\exampleExpectedResult.tsv